services:
  - type: web
    name: cat-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci
    startCommand: node index.js
    envVars:
      - key: DB_NAME
        fromDatabase:
          name: cat_app_database
          property: database
      - key: DB_USER
        fromDatabase:
          name: cat_app_database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cat_app_database
          property: password
      - key: DB_HOST
        fromDatabase:
          name: cat_app_database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cat_app_database
          property: port